{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "7d31a3c3-fbaa-4ed2-863d-ce4430afd78b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ingolstadt7 C:\\Users\\nahed\\RESCO\\environments/ingolstadt7/ingolstadt7.sumocfg ma2c wait\n",
      "[DEBUG]: ['C:\\\\Program Files (x86)\\\\Eclipse\\\\Sumo\\\\bin\\\\sumo.exe', '-c', 'C:\\\\Users\\\\nahed\\\\RESCO\\\\environments/ingolstadt7/ingolstadt7.sumocfg', '--no-warnings', 'True']\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52088 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52090 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52092 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52094 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52096 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52098 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52103 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52105 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52107 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52109 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52111 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52113 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52115 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52117 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52119 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52121 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52123 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52129 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52131 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52133 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52135 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52139 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52141 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52143 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52145 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52148 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52150 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52152 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52155 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52157 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52159 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52161 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52163 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52167 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52169 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52171 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52176 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52178 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52180 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52182 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52184 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52186 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52188 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52190 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52192 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52194 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52196 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52198 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52200 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52202 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52204 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52209 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52211 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52213 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52215 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52217 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52219 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52221 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52223 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52225 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n",
      "C:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:154: UserWarning: Could not connect to TraCI server using port 52227 (TraCI server already finished). Retrying with different port.\n",
      "  warnings.warn((\"Could not connect to TraCI server using port %s (%s).\" +\n"
     ]
    },
    {
     "ename": "FatalTraCIError",
     "evalue": "Could not connect.",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mFatalTraCIError\u001b[0m                           Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[8], line 23\u001b[0m\n\u001b[0;32m      6\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mresco_benchmark\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mmain\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m run_trial\n\u001b[0;32m      8\u001b[0m args \u001b[38;5;241m=\u001b[39m SimpleNamespace(\n\u001b[0;32m      9\u001b[0m     agent\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mMA2C\u001b[39m\u001b[38;5;124m'\u001b[39m,\n\u001b[0;32m     10\u001b[0m     \u001b[38;5;28mmap\u001b[39m\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mingolstadt7\u001b[39m\u001b[38;5;124m'\u001b[39m,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m     20\u001b[0m     load\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mFalse\u001b[39;00m\n\u001b[0;32m     21\u001b[0m )\n\u001b[1;32m---> 23\u001b[0m \u001b[43mrun_trial\u001b[49m\u001b[43m(\u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43margs\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mtr\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32m~\\RESCO\\resco_benchmark\\main.py:87\u001b[0m, in \u001b[0;36mrun_trial\u001b[1;34m(args, trial)\u001b[0m\n\u001b[0;32m     84\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m args\u001b[38;5;241m.\u001b[39mmap \u001b[38;5;241m==\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mgrid4x4\u001b[39m\u001b[38;5;124m'\u001b[39m \u001b[38;5;129;01mor\u001b[39;00m args\u001b[38;5;241m.\u001b[39mmap \u001b[38;5;241m==\u001b[39m \u001b[38;5;124m'\u001b[39m\u001b[38;5;124marterial4x4\u001b[39m\u001b[38;5;124m'\u001b[39m:\n\u001b[0;32m     85\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m os\u001b[38;5;241m.\u001b[39mpath\u001b[38;5;241m.\u001b[39mexists(route): \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mEnvironmentError\u001b[39;00m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mYou must decompress environment files defining traffic flow\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m---> 87\u001b[0m env \u001b[38;5;241m=\u001b[39m \u001b[43mMultiSignal\u001b[49m\u001b[43m(\u001b[49m\u001b[43malg\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[38;5;18;43m__name__\u001b[39;49m\u001b[38;5;241;43m+\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43m-tr\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;241;43m+\u001b[39;49m\u001b[38;5;28;43mstr\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mtrial\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     88\u001b[0m \u001b[43m                  \u001b[49m\u001b[43margs\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmap\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     89\u001b[0m \u001b[43m                  \u001b[49m\u001b[43mos\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mpath\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mjoin\u001b[49m\u001b[43m(\u001b[49m\u001b[43margs\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mpwd\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmap_config\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mnet\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m]\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     90\u001b[0m \u001b[43m                  \u001b[49m\u001b[43magt_config\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mstate\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m]\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     91\u001b[0m \u001b[43m                  \u001b[49m\u001b[43magt_config\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mreward\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m]\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     92\u001b[0m \u001b[43m                  \u001b[49m\u001b[43mroute\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mroute\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mstep_length\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mmap_config\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mstep_length\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m]\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43myellow_length\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mmap_config\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43myellow_length\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m]\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     93\u001b[0m \u001b[43m                  \u001b[49m\u001b[43mstep_ratio\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mmap_config\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mstep_ratio\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m]\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mend_time\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mmap_config\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mend_time\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m]\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     94\u001b[0m \u001b[43m                  \u001b[49m\u001b[43mmax_distance\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43magt_config\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mmax_distance\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m]\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mlights\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mmap_config\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mlights\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m]\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mgui\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43margs\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mgui\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     95\u001b[0m \u001b[43m                  \u001b[49m\u001b[43mlog_dir\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43margs\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mlog_dir\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mlibsumo\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43margs\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mlibsumo\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mwarmup\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mmap_config\u001b[49m\u001b[43m[\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mwarmup\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m]\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     97\u001b[0m agt_config[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mepisodes\u001b[39m\u001b[38;5;124m'\u001b[39m] \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mint\u001b[39m(args\u001b[38;5;241m.\u001b[39meps \u001b[38;5;241m*\u001b[39m \u001b[38;5;241m0.8\u001b[39m)    \u001b[38;5;66;03m# schedulers decay over 80% of steps\u001b[39;00m\n\u001b[0;32m     98\u001b[0m agt_config[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124msteps\u001b[39m\u001b[38;5;124m'\u001b[39m] \u001b[38;5;241m=\u001b[39m agt_config[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mepisodes\u001b[39m\u001b[38;5;124m'\u001b[39m] \u001b[38;5;241m*\u001b[39m num_steps_eps\n",
      "File \u001b[1;32m~\\RESCO\\resco_benchmark\\multi_signal.py:46\u001b[0m, in \u001b[0;36mMultiSignal.__init__\u001b[1;34m(self, run_name, map_name, net, state_fn, reward_fn, route, gui, end_time, step_length, yellow_length, step_ratio, max_distance, lights, log_dir, libsumo, warmup, gymma)\u001b[0m\n\u001b[0;32m     44\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39msumo \u001b[38;5;241m=\u001b[39m traci\n\u001b[0;32m     45\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m---> 46\u001b[0m     \u001b[43mtraci\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mstart\u001b[49m\u001b[43m(\u001b[49m\u001b[43msumo_cmd\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mlabel\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mconnection_name\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     47\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39msumo \u001b[38;5;241m=\u001b[39m traci\u001b[38;5;241m.\u001b[39mgetConnection(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mconnection_name)\n\u001b[0;32m     48\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39msignal_ids \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39msumo\u001b[38;5;241m.\u001b[39mtrafficlight\u001b[38;5;241m.\u001b[39mgetIDList()\n",
      "File \u001b[1;32mC:\\Program Files (x86)\\Eclipse\\Sumo\\tools\\traci\\main.py:157\u001b[0m, in \u001b[0;36mstart\u001b[1;34m(cmd, port, numRetries, label, verbose, traceFile, traceGetters, stdout, doSwitch)\u001b[0m\n\u001b[0;32m    154\u001b[0m         warnings\u001b[38;5;241m.\u001b[39mwarn((\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mCould not connect to TraCI server using port \u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m (\u001b[39m\u001b[38;5;132;01m%s\u001b[39;00m\u001b[38;5;124m).\u001b[39m\u001b[38;5;124m\"\u001b[39m \u001b[38;5;241m+\u001b[39m\n\u001b[0;32m    155\u001b[0m                        \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m Retrying with different port.\u001b[39m\u001b[38;5;124m\"\u001b[39m) \u001b[38;5;241m%\u001b[39m (sumoPort, e))\n\u001b[0;32m    156\u001b[0m         numRetries \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m=\u001b[39m \u001b[38;5;241m1\u001b[39m\n\u001b[1;32m--> 157\u001b[0m \u001b[38;5;28;01mraise\u001b[39;00m FatalTraCIError(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mCould not connect.\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n",
      "\u001b[1;31mFatalTraCIError\u001b[0m: Could not connect."
     ]
    }
   ],
   "source": [
    "import sys, os\n",
    "from types import SimpleNamespace\n",
    "\n",
    "sys.path.append(os.getcwd())\n",
    "\n",
    "from resco_benchmark.main import run_trial\n",
    "\n",
    "args = SimpleNamespace(\n",
    "    agent='MA2C',\n",
    "    map='ingolstadt7',\n",
    "    eps=2,\n",
    "    trials=1,\n",
    "    procs=1,\n",
    "    pwd=os.path.abspath(''), \n",
    "    log_dir=os.path.join(os.getcwd(), 'results'),\n",
    "    gui=False,\n",
    "    libsumo=False,\n",
    "    tr=0,\n",
    "    save_freq=100,\n",
    "    load=False\n",
    ")\n",
    "\n",
    "run_trial(args, args.tr)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "5bf2bf66-b973-4e3b-ac06-a99fc66ac8f6",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "dict_keys(['MAXWAVEVAL', 'MAXPRESSUREVAL', 'MPLightVAL', 'FMA2CVAL', 'STOCHASTIC', 'MAXWAVE', 'MAXPRESSURE', 'IDQN', 'IPPO', 'MPLight', 'FMA2C', 'MPLightFULL', 'FMA2CFULL'])\n"
     ]
    }
   ],
   "source": [
    "import resco_benchmark.config.agent_config as ac\n",
    "print(ac.agent_configs.keys())\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
